[package]
name = "chaty-utils"
version = "0.1.3"
edition = "2024"
license = "MIT"
authors = ["Ahmad Khatib <ahmadkhatib923@gmail.com>"]
description = "Chaty Backend: helpers, utils ..."

[dependencies]
chrono = "0.4.41"
